/* eslint @typescript-eslint/no-var-requires: 0 */
const express = require('express')
const cheerio = require('cheerio')
const path = require('path')
const fs = require('fs')
const metaDataObj = require('./src/Constants/metaData.json')
const axios = require('axios')
const { cmsBaseDomain } = require('./src/Constants/appSettings')
//import { cmsBaseDomain } from './src/Constants/appSettings' 

const PORT = 5500

const app = express()

const options = {
  dotfiles: 'ignore',
  etag: false,
  extensions: ['htm', 'html', 'js', 'css', 'json', 'ico', 'png', 'jpg', 'txt', 'svg', 'woff', 'woff2', 'webp', 'map'],
  index: false,
  maxAge: '0',
  redirect: 'false',
  setHeaders: (res) => {
    res.set('x-timestamp', Date.now())
  },
}



//metaDataObj[correctPath] || await getBlogsMeta(correctPath)

const getMetaData = async (path) => {
  let pathName = path.slice(1)
  try {
    const res = await axios.get(
      `${cmsBaseDomain}/seometatags/?pagePath=${pathName}`
    )
    let data = res.data.data.meta
    let headers = {
      title: '',
      links: [],
      metaData: [],
      script: '',
    }

    data = data.replace(/\\n/g, '')
    data = data.split('\n')
    data.forEach((el) => {
      if (el.includes('<meta') || el.includes('<link')) {
        let obj = {}
        let regExp = /(\S+)="[^"]*/g
        let regexMatches = el.match(regExp)

        regexMatches.map((el) => {
          let partition = el.split('="')
          obj[partition[0]] = partition[1].replace(/"/g, '')
        })

        if (el.includes('<meta')) headers.metaData.push(obj)
        if (el.includes('<link')) headers.links.push(obj)
      } else if (el.includes('<title')) {
        headers.title = el.replace('<title>', '').replace('</title>', '')
      }
      else if (el.includes('<script')) headers.script = el
    })
    return { ...headers, h1Tag: metaDataObj?.[path]?.h1Tag, h2Tags: metaDataObj?.[path?.h2Tags], pTag: res.data.data?.pTag, aTags: res.data.data?.relatedCourses }
  } catch (err) {
    if (metaDataObj[path]) return metaDataObj[path]
    try {
      const res = await axios.get(`${cmsBaseDomain}/post${path}`)
      let data = res.data.data.meta
      let headers = {
        title: '',
        links: [],
        metaData: [],
        script: '',
        h1Tag: '',
        pTagBlog: res.data.data.content
      }
      headers.h1Tag = res.data.data.title
      data = data.replace(/\\n/g, '')
      data = data.split('\n')
      data.forEach((el) => {
        if (el.includes('<meta') || el.includes('<link')) {
          let obj = {}
          let regExp = /(\S+)="[^"]*/g
          let regexMatches = el.match(regExp)

          regexMatches.map(el => {
            let partition = el.split('="')
            obj[partition[0]] = partition[1].replace(/"/g, '')
          })

          if (el.includes('<meta'))
            headers.metaData.push(obj)
          if (el.includes('<link'))
            headers.links.push(obj)
        }
        else if (el.includes('<title')) {
          headers.title = el.replace('<title>', '').replace('</title>', '')
        }
        else if (el.includes('<script'))
          headers.script = el

      })
      return headers
    } catch (err) {
      // console.log(err)
    }
  }
}
const getBogLinks = async () => {
  const { data } = await axios.get(`${cmsBaseDomain}/misc/urlsarray`)
  return data.data
}
const RemoveTrailingSlash = (url) => {

  if (url.endsWith("/") && url !== "/") {
    const newPath = url.slice(0, -1);
    return newPath;
  }

  return url;
};

const redirectPage = async (path) => {//used to redirected non existing links
  let links404 = [
    "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-ch-1-sutra-10-parisamvad",
    "https://theyogainstitute.org/yoganew/dr-jayadeva-talking-saucha-purity",
    "https://theyogainstitute.org/yoganew/how-can-yoga-help-students-alleviate-examination-stress-and-make-them-perform-better",
    "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-2-5-parisamvad",
    "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-51-parisamvad",
    "https://theyogainstitute.org/yoganew/can-yoga-help-in-psychosomatic-disease",
    "https://theyogainstitute.org/yoganew/3-day-holistic-wellness-yoga-retreat-france",
    "https://theyogainstitute.org/yoganew/the-yoga-institute-conducted-yoga-sessions-for-sadhu-vaswani-mission",
    "https://theyogainstitute.org/yoganew/diy-quick-top-5-yoga-tips-to-keep-the-exam-stress-at-bay",
    "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-14th-april-17th-april",
    "https://theyogainstitute.org/yoganew/conditioning-yoga",
    "https://theyogainstitute.org/yoganew/yoga-tips-reduce-side-fat",
    "https://theyogainstitute.org/yoganew/dishonesty-is-not-the-best-policy-dr-jayadeva-yogendra",
    "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-30-parisamvad",
    "https://theyogainstitute.org/yoganew/corporate-workshops",
    "https://theyogainstitute.org/yoganew/importance-of-sleep-in-our-daily-life",
    "https://theyogainstitute.org/yoganew/drawing-a-line",
    "https://theyogainstitute.org/yoganew/qa-on-change-yourself",
    "https://theyogainstitute.org/yoganew/dr-jayadeva-on-paramhamsa-madhavadasji-overcoming-bad-habits-at-the-satsang-3rd-jan-2013",
    "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-yogendra-8th-11th-june-2013",
    "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-6th-april-10th-april",
    "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-30th-march-4th-april",
    "https://theyogainstitute.org/yoganew/q-a-on-sanskaras-values-at-the-satsang-13th-jan-2013",
    "https://theyogainstitute.org/yoganew/hansaji-talking-saints-india",
    "https://theyogainstitute.org/yoganew/june-2011-editorial",
    "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-18-24-may-2013",
    "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-24th-30th-aug-2013",
    "https://theyogainstitute.org/yoganew/dr-jayadeva-on-positive-thinking-at-the-satsang",
    "https://theyogainstitute.org/yoganew/sincere-commitment",
    "https://theyogainstitute.org/yoganew/dr-jayadeva-talking-on-tension-and-relaxation",
    "https://theyogainstitute.org/yoganew/dr-jayadeva-on-sanskaras-values-at-the-satsang-13th-jan-2013",
    "https://theyogainstitute.org/yoganew/qa-on-saints-of-india-at-the-satsang-14th-april-2013",
    "https://theyogainstitute.org/yoganew/every-moment-a-wonder",
    "https://theyogainstitute.org/June",
    "https://theyogainstitute.org/Konasana%E2%80%93the-Angle-Pose-a-guide-to-konasana-benefits-and-techniques",
    "https://theyogainstitute.org/diet-workshop",
    "https://theyogainstitute.org/5th-international-day-of-yoga",
    "https://theyogainstitute.org/konasana-the-angle-pose",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english-nov-dec",
    "https://theyogainstitute.org/null",
    "https://theyogainstitute.org/21-days-better-living-course-batch-4",
    "https://theyogainstitute.org/Celebrating",
    "https://theyogainstitute.org/senior-citizen-workshop",
    "https://theyogainstitute.org/%E0%A5%90-aum-a-success-mantra",
    "https://theyogainstitute.org/6-relaxation-techniques-for-stress",
    "https://theyogainstitute.org/good-food-fest",
    "https://theyogainstitute.org/patanjali-yoga-sutra-1-38",
    "https://theyogainstitute.org/terms-and-condition",
    "https://theyogainstitute.org/vacation-camp-children",
    "https://theyogainstitute.org/raipur",
    "https://theyogainstitute.org/virtual-tour-the-yoga-institute-exterior",
    "https://theyogainstitute.org/free-yoga-camps",
    "https://theyogainstitute.org/can-meditation-replace-medication",
    "https://theyogainstitute.org/blog",
    "https://theyogainstitute.org/meditation-camp",
    "https://theyogainstitute.org/weekend",
    "https://theyogainstitute.org/7-days-online-yoga-camp",
    "https://theyogainstitute.org/Poses",
    "https://theyogainstitute.org/5-powerful-ways-to-hit-the-pa",
    "https://theyogainstitute.org/spain-english",
    "https://theyogainstitute.org/index.html",
    "https://theyogainstitute.org/free-yoga-online-camps",
    "https://theyogainstitute.org/print-media/Bulletins",
    "https://theyogainstitute.org/yoga-sutra-isvara-pranidhanat",
    "https://theyogainstitute.org/Boost",
    "https://theyogainstitute.org/thank-you-hindi-ttc-registration",
    "https://theyogainstitute.org/yoga-and-total-healthT",
    "https://theyogainstitute.org/italy",
    "https://theyogainstitute.org/what-is-sattvic-diet/10",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-camp-form-lp",
    "https://theyogainstitute.org/importance-of-the-spine-in-yoga/sitting-vakrasana-twist",
    "https://theyogainstitute.org/product/how-to-train-the-subconscious-mind",
    "https://theyogainstitute.org/yoga-calendar",
    "https://theyogainstitute.org/what-is-sattvic-diet/common",
    "https://theyogainstitute.org/900-hours-advanced-teach",
    "https://theyogainstitute.org/what-is-sattvic-diet/wrestling",
    "https://theyogainstitute.org/what-is-sattvic-diet/terms",
    "https://theyogainstitute.org/Planning",
    "https://theyogainstitute.org/publications.htm",
    "https://theyogainstitute.org/about_us.htm",
    "https://theyogainstitute.org/Managing",
    "https://theyogainstitute.org/quotes",
    "https://theyogainstitute.org/Yoga%E2%80%99s",
    "https://theyogainstitute.org/The",
    "https://theyogainstitute.org/what-is-sattvic-diet/cricket",
    "https://theyogainstitute.org/Kaivalyadham",
    "https://theyogainstitute.org/Mumbai",
    "https://theyogainstitute.org/Meditative",
    "https://theyogainstitute.org/5-kleshas-root-causes-of-suffering-in-life/practice \nof yoga",
    "https://theyogainstitute.org/Yoga for painful shoulders",
    "https://theyogainstitute.org/If",
    "https://theyogainstitute.org/easy-ways-to-ease-anxiety/Dhanurasana",
    "https://theyogainstitute.org/newsletters",
    "https://theyogainstitute.org/Why",
    "https://theyogainstitute.org/what-is-unconditional-love",
    "https://theyogainstitute.org/yoga-total-health-journal-magazine",
    "https://theyogainstitute.org/certification-course-on-yoga-sutra-online",
    "https://theyogainstitute.org/3-months-superior-teacher-training-course",
    "https://theyogainstitute.org/shop/cart",
    "https://theyogainstitute.org/few-yoga-handy",
    "https://theyogainstitute.org/blog/mother-sita-devis-birth-anniversary-celebrations",
    "https://theyogainstitute.org/3-month-ttc",
    "https://theyogainstitute.org/yoga-asanas-dos",
    "https://theyogainstitute.org/Complete",
    "https://theyogainstitute.org/yoga-asanas-dos-and",
    "https://theyogainstitute.org/definition/mantra",
    "https://theyogainstitute.org/goa-ttc-camp-form",
    "https://theyogainstitute.org/full-moon-meditation",
    "https://theyogainstitute.org/blog/drawing-a-line",
    "https://theyogainstitute.org/blog/dr-jayadeva-on-yoga-for-the-golden-years-at-the-santsang-17th-feb-2013",
    "https://theyogainstitute.org/blog/dr-jayadeva-on-paramhamsa-madhavadasji-overcoming-bad-habits-at-the-satsang-3rd-jan-2013",
    "https://theyogainstitute.org/blog/hansaji-talking-on-asteya-non-stealing",
    "https://theyogainstitute.org/blog/Official",
    "https://theyogainstitute.org/yoga-therapy-course",
    "https://theyogainstitute.org/product-category/regular-classes/weekend-yoga-regular-classes",
    "https://theyogainstitute.org/counselling-service",
    "https://theyogainstitute.org/a-simple-guide-to-meditation-for-beginners",
    "https://theyogainstitute.org/kids-camp",
    "https://theyogainstitute.org/product/online-swadhyay-english",
    "https://theyogainstitute.org/thank-you-ttc-registration-on-campus-sp",
    "https://theyogainstitute.org/happy-teachers-day-2017",
    "https://theyogainstitute.org/gallery-golden-book-of-world-records",
    "https://theyogainstitute.org/payment-status",
    "https://theyogainstitute.org/Empowering",
    "https://theyogainstitute.org/yoga-poses",
    "https://theyogainstitute.org/performance-by-sukhwinder-singh",
    "https://theyogainstitute.org/product/yogic-life-for-control-of-diabetes-hansaji-armaiti-desai",
    "https://theyogainstitute.org/stable-mind-stable-health",
    "https://theyogainstitute.org/category/satsang",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-camp-form-english",
    "https://theyogainstitute.org/high-vibration-people-definition,-signs,-and-how-to-become-one",
    "https://theyogainstitute.org/rooftop-space",
    "https://theyogainstitute.org/parisamvad",
    "https://theyogainstitute.org/curso-de-formaci",
    "https://theyogainstitute.org/ganesh-chaturthi-2017",
    "https://theyogainstitute.org/whats_new.htm",
    "https://theyogainstitute.org/the-store-of-the-yoga-institute/%3Cacessado",
    "https://theyogainstitute.org/product/7-days-camp-insight-into-yoga-non-residential-hindi-may",
    "https://theyogainstitute.org/Sign",
    "https://theyogainstitute.org/21-days-better-living",
    "https://theyogainstitute.org/Bulletins",
    "https://theyogainstitute.org/trataka.yogic.eyecare",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-on",
    "https://theyogainstitute.org/900-hour",
    "https://theyogainstitute.org/900-hours-advanced",
    "https://theyogainstitute.org/yoga%20to%20increase%20immunity",
    "https://theyogainstitute.org/Yoga%20Asanas%20Do%E2%80%99s%20and%20Don%E2%80%99ts%20for%20Beginners",
    "https://theyogainstitute.org/200-hrs-part-time-ttc",
    "https://theyogainstitute.org/Sleep",
    "https://theyogainstitute.org/product/online-stress",
    "https://theyogainstitute.org/product/7-days-camp-insight-into-yoga-residential-nov",
    "https://theyogainstitute.org/parisamwad.htm",
    "https://theyogainstitute.org/Face",
    "https://theyogainstitute.org/Exploring",
    "https://theyogainstitute.org/Reputable",
    "https://theyogainstitute.org/donation/62da3b1e4b905a0012149926",
    "https://theyogainstitute.org/yoga-asanas-for-healthy-mind-and-body%3E",
    "https://theyogainstitute.org/one-mont",
    "https://theyogainstitute.org/7-days-camp/Register",
    "https://theyogainstitute.org/and",
    "https://theyogainstitute.org/one-month-ttc/Register",
    "https://theyogainstitute.org/product/online-patanjalis",
    "https://theyogainstitute.org/patanjali-yoga-sutra-2-16-paris",
    "https://theyogainstitute.org/wellness-camps",
    "https://theyogainstitute.org/product/online-swadhyay",
    "https://theyogainstitute.org/asana-regular-classes-on",
    "https://theyogainstitute.org/qwertyqwerty",
    "https://theyogainstitute.org/yoga",
    "https://theyogainstitute.org/yoga-halls",

    "https://theyogainstitute.org/emotional-intelligence-workshop/",
   "https://theyogainstitute.org/wp-content/uploads/2020/05/FAQ's-for-2MTTC_25th-May-2020.pdf",
  "https://theyogainstitute.org/teacher-training-course",
  "https://theyogainstitute.org/indore",
  "https://theyogainstitute.org/one-year-ttc/Register",
  "https://theyogainstitute.org/yoganew/how-to-do-bhadrasana",
  "https://theyogainstitute.org/7-",
  "https://theyogainstitute.org/how-",
  "https://theyogainstitute.org/tag/nishpanda-bhava",
  "https://theyogainstitute.org/what-is-sattvic-diet/benefit",
  "https://theyogainstitute.org/Exploring-he-Link-Between-Yoga-Meditation-and-Reproductive-Health",
  "https://theyogainstitute.org/ashwa-sanchalanasana",
  "https://theyogainstitute.org/what-is-sattvic-diet/4th",
  "https://theyogainstitute.org/how-to",
  "https://theyogainstitute.org/tag/workout",
  "https://theyogainstitute.org/discover-5-types-of-pranayamas-and-their-benefits",
  "https://theyogainstitute.org/patanjali-yoga-sutra-",
  "https://theyogainstitute.org/etymology-of-mantra.wisdomlib.com/2/7054/meditation/mantra/om-namah-shivaya-mantra",
  "https://theyogainstitute.org/yoganew/bhagwad-gita-sloka-2-59-parisamvad",
  "https://theyogainstitute.org/undefined",
  "https://theyogainstitute.org/counselling-services",
  "https://theyogainstitute.org/patanjali-yoga-sutra-1-25-parisamvad/patanjali-yoga-sutra-1-25",
  "https://theyogainstitute.org/one-month-ttc/Phone",
  "https://theyogainstitute.org/tag/june",
  "https://theyogainstitute.org/tag/reflection-and-meditation",
  "https://theyogainstitute.org/yoganew/conference-room",
  "https://theyogainstitute.org/why-we-need-pain-to-experience-happiness.",
  "https://theyogainstitute.org/[object",
  "https://theyogainstitute.org/tag/yoga-twist-benefits",
  "https://theyogainstitute.org/special-regular-classes",
  "https://theyogainstitute.org/tag/life-management",
  "https://theyogainstitute.org/tag/duty",
  "https://theyogainstitute.org/3-yoga-exercise-to-reduce-love-handles-yoga-for-love-handles3",
  "https://theyogainstitute.org/bahirang-the-external-aspect-of-the-8-fold-path-of-yoga",
  "https://theyogainstitute.org/tag/anger-control",
  "https://theyogainstitute.org/yoga-sessions-for-sadhu-vaswani-mission",
  "https://theyogainstitute.org/blog/patanjali-yoga-sutra-2-13-parisamvad",
  "https://theyogainstitute.org/regular-yoga-asana-",
  "https://theyogainstitute.org/results",
  "https://theyogainstitute.org/one-year-ttc/We",
  "https://theyogainstitute.org/product/yoga-and-total-health-subscription-india-only",
  "https://theyogainstitute.org/what-is-sattvic-diet/suhagraat",
  "https://theyogainstitute.org/yoga-psychotherapy-curriculum",
  "https://theyogainstitute.org/tag/earning-money",
  "https://theyogainstitute.org/gallery-swami-ramdevji-visited-yoga-institute/dr-jayadeva-yogendraji-with-swami-ramdevji",
  "https://theyogainstitute.org/yoganew/qa-on-inter-personal-relations-at-the-satsang-24th-feb-2013",
  "https://theyogainstitute.org/commemoration-of-shri-yogendra-chowk",
  "https://theyogainstitute.org/yoganew/hansaji-on-positive-thinking-at-the-satsang",
  "https://theyogainstitute.org/andheri-west",
  "https://theyogainstitute.org/product-tag/online-swadhyay",
  "https://theyogainstitute.org/seven-month-ttc/7-month-ttc-the-yoga-institute-mumbai//1000",
  "https://theyogainstitute.org/blog/patanjali-yoga-sutra-1-28-parisamvad",
  "https://theyogainstitute.org/what-is-sattvic-diet/awa",
  "https://theyogainstitute.org/tag/yogaeveryday",
  "https://theyogainstitute.org/what-is-sattvic-diet/even",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-yamas-at-the-satsang-3rd-march-2013",
  "https://theyogainstitute.org/spain",
  "https://theyogainstitute.org/tag/priority",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-17th-19th-august-2014",
  "https://theyogainstitute.org/one-month",
  "https://theyogainstitute.org/jayadeva_hansaji.htm",
  "https://theyogainstitute.org/yoganew/hansaji-talking-ahimsa",
  "https://theyogainstitute.org/yoganew/weekly-update-dr-jayadeva-talking-on-yoga-26-jan-1-feb-2013",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-29th-september-4th-october",
  "https://theyogainstitute.org/tag/habits",
  "https://theyogainstitute.org/tag/prajna",
  "https://theyogainstitute.org/certificate-program-on-",
  "https://theyogainstitute.org/patanjali-yoga-sutra-The",
  "https://theyogainstitute.org/arogyam",
  "https://theyogainstitute.org/tag/routines",
  "https://theyogainstitute.org/blog/hansaji-talking-positive-rituals",
  "https://theyogainstitute.org/tag/faith",
  "https://theyogainstitute.org/what-is-sattvic-diet/ma",
  "https://theyogainstitute.org/tag/regrets",
  "https://theyogainstitute.org/tag/relationships-2",
  "https://theyogainstitute.org/aimsand-objectives-of-yoga-education",
  "https://theyogainstitute.org/category/astanga-yoga",
  "https://theyogainstitute.org/tag/brahmacharya",
  "https://theyogainstitute.org/yoganew/hong-kong",
  "https://theyogainstitute.org/on-campus-courses",
  "https://theyogainstitute.org/yoga-therapeutics-to-cure-migraines-headaches",
  "https://theyogainstitute.org/product/online-regular-guided-meditation-classes",
  "https://theyogainstitute.org/product/online-yoga-classes-for-kids",
  "https://theyogainstitute.org/juhu-vile-parle",
  "https://theyogainstitute.org/tag/letting-go",
  "https://theyogainstitute.org/ttc-courses",
  "https://theyogainstitute.org/yoganew/yoga-sutra-ch-1-sutra-7-parisamvad",
  "https://theyogainstitute.org/yoganew/saints-of-india-satsang-2",
  "https://theyogainstitute.org/yoganew/digital-media",

  "https://theyogainstitute.org/free-ebooks",
  "https://theyogainstitute.org/product/online-cardiac-and-hypertension-health-workshop",
  "https://theyogainstitute.org/what-is-sattvic-diet/has",
  "https://theyogainstitute.org/tag/insatiable-desires",
  "https://theyogainstitute.org/how-to-maintain-mental-health-in-the-workplace",
  "https://theyogainstitute.org/Busy",
  "https://theyogainstitute.org/yoganew/press-releases",
  "https://theyogainstitute.org/what-is-sattvic-diet/goal",
  "https://theyogainstitute.org/wp-content/uploads/2019/10/YogaSattva-Oct-2019.pdf",
  "https://theyogainstitute.org/yoganew/hansaji-talking-positive-rituals",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-2nd-6th-june-2014",
  "https://theyogainstitute.org/tag/yoga-teacher",
  "https://theyogainstitute.org/product/online-pregnancy-camp",
  "https://theyogainstitute.org/8-common-symptoms-of-depression",
  "https://theyogainstitute.org/category/sept-2010",
  "https://theyogainstitute.org/practical-yogic-guidelines-to-beat-stress/feed",
  "https://theyogainstitute.org/deep-sleep-meditation-techniques-before-sleep",
  "https://theyogainstitute.org/tag/ashtanga-yoga",
  "https://theyogainstitute.org/uruguay",
  "https://theyogainstitute.org/asana-regular-classes-",
  "https://theyogainstitute.org/yoganew/qa-on-aparigraha-at-the-satsang-2nd-june-2013",
  "https://theyogainstitute.org/hansaji-talking-about-sita-devi",
  "https://theyogainstitute.org/stress-management-",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-16th-21st-june-2013",
  "https://theyogainstitute.org/tag/artha",
  "https://theyogainstitute.org/weekly-update-talks-on-yoga-by-dr-jayadeva-yogendra-1st-7th-june-2013",
  "https://theyogainstitute.org/yoganew/weekly-update-dr-jayadeva-talking-on-yoga-2nd-8th-feb-2013",
  "https://theyogainstitute.org/blog/patanjali-yoga-sutra-1-28-parisamvad",
  "https://theyogainstitute.org/smt-hansaji-yogendra-on-purushartha-motivations-at-the-satsang/hansaji-02bright",
  "https://theyogainstitute.org/tag/yogapractice",
  "https://theyogainstitute.org/product/online-ayurveda-diet-and-immunity-workshop",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-on-campus-english-march",
  "https://theyogainstitute.org/celebrating-4th-international-day-of-yoga-at-turtlemint",
  "https://theyogainstitute.org/wp-content/themes/bridge/css/stylesheet.min.css?ver=4.5.3",
  "https://theyogainstitute.org/childrens-",
  "https://theyogainstitute.org/weekend-teacher-training-courseRegister",
  "https://theyogainstitute.org/yoga-explore",
  "https://theyogainstitute.org/tag/mindfulness",
  "https://theyogainstitute.org/tag/yogainspiration",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-22nd-february-28th-february-2014",
  "https://theyogainstitute.org/tag/yogi",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-22nd-27th-june-2014",
  "https://theyogainstitute.org/tag/satya",
  "https://theyogainstitute.org/tag/saints",
  "https://theyogainstitute.org/master-strokes-vol-1-front-cover",
  "https://theyogainstitute.org/wp-content/themes/bridge/css/stylesheet.min.css?ver=4.5.3;702244",
  "https://theyogainstitute.org/top-7-yoga-posses-for-constipation-relief",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-5th-october-11th-october",
  "https://theyogainstitute.org/yoganew/yoga-sutra-ch-1-sutra-7-parisamvad",
  "https://theyogainstitute.org/regular-",
  "https://theyogainstitute.org/swadhaya-802x1024",
  "https://theyogainstitute.org/dr-jayadeva-talking-satya-truth/feed",
  "https://theyogainstitute.org/7-month-yoga-teacher-training-course-registration-form",
  "https://theyogainstitute.org/yoganew/hastapadasana-the-hands-to-feet-posture",
  "https://theyogainstitute.org/yoganew/yoga-and-menopause",
  "https://theyogainstitute.org/yoganew/the-little-things",
  "https://theyogainstitute.org/yoganew/first-qci-certified-yoga-teacher-training-school-the-yoga-institute-mumbai",
  "https://theyogainstitute.org/yoganew/agnisara-abdomen-contractions",
  "https://theyogainstitute.org/yoganew/happy-88th-birthday-dr-jayadeva-yogic-journey-celebrations",
  "https://theyogainstitute.org/sant-hirdaram-medical-college-of-naturopathy-yogic-sciences-bhopal",
  "https://theyogainstitute.org/yoganew/the-yoga-institute-tyi-yoga-teacher-training-course-level-2",
  "https://theyogainstitute.org/what-is-sattvic-diet/food",
  "https://theyogainstitute.org/yoganew/yoga-sutra-tasya-vachakah-pranavah-1-27",
  "https://theyogainstitute.org/yoganew/parikarmas-in-yoga",
  "https://theyogainstitute.org/understanding-ashtanga-yoga-2",
  "https://theyogainstitute.org/yoganew/hong-kong",
  "https://theyogainstitute.org/yoganew/sauca-niyama-yoga-purity",
  "https://theyogainstitute.org/powai/powai-2",
  "https://theyogainstitute.org/yoganew/conference-room",
  "https://theyogainstitute.org/product-tag/online-swadhyay",
  "https://theyogainstitute.org/product-category/ttc/3-month-ttc",
  "https://theyogainstitute.org/smt-hansaji-yogendras-70th-birthday-celebrations",
  "https://theyogainstitute.org/product-tag/bhavas-workshop",
  "https://theyogainstitute.org/advanced-pranayama-techniques",
  "https://theyogainstitute.org/centenary-logo-unveiling-and-birthday-celebration-of-dr-jayadeva-yogendra",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-16th-march-21st-march",
  "https://theyogainstitute.org/centenary-celebrations-yoga-seminar-the-culture-of-tomorrow",
  "https://theyogainstitute.org/yoganew/halasana-the-plough-pose",
  "https://theyogainstitute.org/yoganew/paramahamsa-madhavdasji-a-true-yogi",
  "https://theyogainstitute.org/blog/patanjali-yoga-sutra-2-11-parisamvad",
  "https://theyogainstitute.org/yoganew/saints-of-india-satsang-2",
  "https://theyogainstitute.org/product-tag/special-regular-classes",
  "https://theyogainstitute.org/advisory-board-committee",
  "https://theyogainstitute.org/yoganew/hansaji-talking-guru-shishya-guru-purnima-day",
  "https://theyogainstitute.org/900-hours-advanced-teacher-training-online-course",
  "https://theyogainstitute.org/category/satya-2",
  "https://theyogainstitute.org/product/online-enhance-immunity-with-ayurveda-workshop",
  "https://theyogainstitute.org/product-category/month/august",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-saints-of-india-at-the-satsang-14th-april-2013",
  "https://theyogainstitute.org/comments/feed",
  "https://theyogainstitute.org/wp-admin/admin-ajax.php",
  "https://theyogainstitute.org/product/21-days-better-living-course-online-hindi",
  "https://theyogainstitute.org/what-is-yoga-therapy-yoga-",
  "https://theyogainstitute.org/yoga-asanas-",
  "https://theyogainstitute.org/yoganew/announcing-the-release-yoga-sutras-of-patanjali-talks-by-dr-jayadeva-smt-hansaji-much-awaited-volume-that-decodes-yoga-as-a-way-of-life",
  "https://theyogainstitute.org/delhi",
  "https://theyogainstitute.org/product/yoga-asanas-simplified-shri-yogendraji",
  "https://theyogainstitute.org/tag/eyeball-rotation",
  "https://theyogainstitute.org/tag/how-to-improve-eye-sight-with-yoga",
  "https://theyogainstitute.org/online-",
  "https://theyogainstitute.org/tag/god",
  "https://theyogainstitute.org/500-hrs-online-yoga-",
  "https://theyogainstitute.org/upcoming-events-list",

  "https://theyogainstitute.org/tag/surya-namaskar",
  "https://theyogainstitute.org/tag/abdominal-pranayama",
  "https://theyogainstitute.org/museum-visits",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-45-parisamvad",
  "https://theyogainstitute.org/yoganew/germans-are-here-15th-may-2016",
  "https://theyogainstitute.org/category/faith-2",

  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-16th-21st-june-2013",
  "https://theyogainstitute.org/shop/wp-content/themes/shopperpress/thumbs/Guide-To-Yoga-Meditation.pdf",
  "https://theyogainstitute.org/tag/62d65f141c38b19586c5c63e",
  "https://theyogainstitute.org/tag/chakra-psychology",
  "https://theyogainstitute.org/tag/breathing-exercise",
  "https://theyogainstitute.org/product/online-pranayama-workshop",
  "https://theyogainstitute.org/arogyam-form",
  "https://theyogainstitute.org/one-month-ttc-landing-page",
  "https://theyogainstitute.org/tag/patanjali",
  "https://theyogainstitute.org/tag/forgive",
  "https://theyogainstitute.org/tag/500-hr-yoga-ttc",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-yogendra-1st-7th-june-2013",
  "https://theyogainstitute.org/relaxation_hansaji_jayadeva_yogendra.htm",
  "https://theyogainstitute.org/pranayama-types-and-",
  "https://theyogainstitute.org/one_year_teachers_training_course.htm",
  "https://theyogainstitute.org/product/online-meditation-workshop",
  "https://theyogainstitute.org/yoganew/weekly-update-dr-jayadeva-talking-on-yoga-23-feb-1-mar-2013",
  "https://theyogainstitute.org/category/yoga-twist",
  "https://theyogainstitute.org/tag/yoga-twist-asanas",
  "https://theyogainstitute.org/sant-hirdaram-medical-college-of-naturopathy-yogic-sciences-bhopal",
  "https://theyogainstitute.org/yoganew/master-strokes-vol-2",
  "https://theyogainstitute.org/tag/postpartum-care",
  "https://theyogainstitute.org/blog/qa-disciplines-routines",
  "https://theyogainstitute.org/blog/the-price-for-honesty",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jaydeva-31st-december-2013-3rd-jan-2014",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-talking-stability-asanas",
  "https://theyogainstitute.org/blog/dr-jayadeva-talking-satya-truth",
  "https://theyogainstitute.org/yoganew/qa-on-overcoming-bad-habits-at-the-satsang-3rd-jan-2013",
  "https://theyogainstitute.org/yoganew/qa-on-physical-culture-vs-yoga-education-at-the-satsang-6th-jan-2013",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-10th-12th-august",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-15th-december-19th-december-2013",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-1st-march-7th-march-2014",
  "https://theyogainstitute.org/3-month-ttc-camp-form-online-course",
  "https://theyogainstitute.org/what-is-sattvic-diet/Diosvelis",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-asteya-at-the-satsang-19th-may-2013",
  "https://theyogainstitute.org/yoganew/diy-top-10-tips-to-remove-holi-color",
  "https://theyogainstitute.org/yoga-museum",
  "https://theyogainstitute.org/tag/reflection-and-meditation",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-5th-july-8th-july-2014",
  "https://theyogainstitute.org/yoganew/yogendra-pawanmuktasana-cultural-yoga-asanas-for-abdomen-compression",
  "https://theyogainstitute.org/yoganew/the-little-things",
  "https://theyogainstitute.org/yoganew/the-yoga-institute-tyi-yoga-teacher-training-course-level-2",
  "https://theyogainstitute.org/yoganew/parikarmas-in-yoga",
  "https://theyogainstitute.org/yoganew/yoga-sutra-tasya-vachakah-pranavah-1-27",
  "https://theyogainstitute.org/yoganew/happy-88th-birthday-dr-jayadeva-yogic-journey-celebrations",
  "http:/www.kdham.com",
  "https://theyogainstitute.org/tag/aparigraha",
  "https://theyogainstitute.org/tag/why",
  "https://theyogainstitute.org/tag/life-management",
  "https://theyogainstitute.org/tag/lower-back-pain-or-discomfort",
  "https://theyogainstitute.org/tag/paramhamsa-madhavadasji",
  "https://theyogainstitute.org/tag/how-to-do-bow-pose",
  "https://theyogainstitute.org/bahirang-the-external-aspect-of-the-8-fold-path-of-yoga",
  "https://theyogainstitute.org/yoganew/announcing-the-release-yoga-sutras-of-patanjali-talks-by-dr-jayadeva-smt-hansaji-much-awaited-volume-that-decodes-yoga-as-a-way-of-life",
  "https://theyogainstitute.org/tag/weightloss",
  "https://theyogainstitute.org/category/q-a",
  "https://theyogainstitute.org/category/sauca",
  "https://theyogainstitute.org/tag/mango-drink-recipe",
  "https://theyogainstitute.org/tag/yoga-for-heart-blockage",
  "https://theyogainstitute.org/tag/500-hour-yoga-ttc",
  "https://theyogainstitute.org/few-yoga-",
  "https://theyogainstitute.org/tag/yogaeverydamnday",
  "https://theyogainstitute.org/tag/yogalife",
  "https://theyogainstitute.org/tag/residential-yoga-training",
  "https://theyogainstitute.org/tag/yogalove",
  "https://theyogainstitute.org/tag/samadhi",
  "https://theyogainstitute.org/yoganew/first-qci-certified-yoga-teacher-training-school-the-yoga-institute-mumbai",
  "https://theyogainstitute.org/tag/parisamvad",
  "https://theyogainstitute.org/tag/cleanliness",
  "https://theyogainstitute.org/page/2/?s=Event",
  "https://theyogainstitute.org/page/2?s=Event",
  "https://theyogainstitute.org/tag/weekly-update",
  "https://theyogainstitute.org/tag/62d65f171c38b19586c5c8a2",
  "https://theyogainstitute.org/6-steps-for-calming-anger",
  "https://theyogainstitute.org/img_0574",
  "https://theyogainstitute.org/yoganew/agnisara-abdomen-contractions",
  "https://theyogainstitute.org/upcoming-events-list",
  "https://theyogainstitute.org/yoganew/yoga-and-menopause",
  "https://theyogainstitute.org/weekend-teacher-coaching-class",
  "https://theyogainstitute.org/tag/angry",
  "https://theyogainstitute.org/tag/62d65f0b1c38b19586c5c118",
  "https://theyogainstitute.org/tag/bkc",
  "https://theyogainstitute.org/tag/benefit-jalaneti",
  "https://theyogainstitute.org/tag/everyday-life",
  "https://theyogainstitute.org/discover-5-types-of-pranayamas-and-their-benefits",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-yamas-at-the-satsang-3rd-march-2013",
  "https://theyogainstitute.org/yoga-for-cancer-rehabilitation-recovery",
  "https://theyogainstitute.org/vibes-at-harmony-fest",
  "https://theyogainstitute.org/product-tag/3-month-ttc",
  "https://theyogainstitute.org/tag/bhramacharya",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-45-parisamvad",
  "https://theyogainstitute.org/yoga-for-asthma/asthama",
  "https://theyogainstitute.org/yoganew/weekly-update-dr-jayadeva-talking-on-yoga-26-jan-1-feb-2013",
  "https://theyogainstitute.org/tag/top-5-yoga-ideas-relax-in-5-minutes",
  "https://theyogainstitute.org/seven-month-ttc-registration-form",
  "https://theyogainstitute.org/yoganew/saints-of-india-satsang",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-29th-september-4th-october",
  "https://theyogainstitute.org/tag/prajna",
  "https://theyogainstitute.org/tag/habits",
  "https://theyogainstitute.org/product-category/regular-classes/special-regular-classes",
  "https://theyogainstitute.org/gallery-120th-birth-anniversary-of-founder-curtain-raiser-for-centenary/media-coverage-of-the-dignitaries-2",
  "https://theyogainstitute.org/blog/what-should-we-aim-for-and-work-towards",
  "https://theyogainstitute.org/ayurveda-food-nutrition-workshop",
  "https://theyogainstitute.org/tag/opinions",
  "https://theyogainstitute.org/gallery-97th-foundation-day-celebration-evening-event",
  "https://theyogainstitute.org/yoganew/qa-yoga-interpersonal-relationships",
  "https://theyogainstitute.org/product/online-",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english-batch-6",
  "https://theyogainstitute.org/yoganew/chakrasana-the-wheel-pose",
  "https://theyogainstitute.org/tag/faith",
  "https://theyogainstitute.org/21-days-better-living-course/21-day-better-living-course-the-yoga-institute-mumbai",
  "https://theyogainstitute.org/thank-you-one-month-ttc-200-hours-registration-sp",
  "https://theyogainstitute.org/tag/routines",
  "https://theyogainstitute.org/tag/regrets",
  "https://theyogainstitute.org/level-3-diploma-program-in-yoga-counselling",
  "https://theyogainstitute.org/gallery-swami-ramdevji-visited-yoga-institute/dr-jayadeva-yogendraji-with-swami-ramdevji",
  "https://theyogainstitute.org/international-yoga-festival-rishikesh/dr-hansaji-participated-in-the-ganga-aarti-along-with-baba-ramdev-ji-swami-chidanand-saraswati-ji-bhanu-didi-shri-kailash-kher",
  "https://theyogainstitute.org/faqs",
  "https://theyogainstitute.org/how-can-yoga-help-with-stress-that-seems-unmanageable",
  "https://theyogainstitute.org/yoganew/householder-yoga-why-convention-2012",
  "https://theyogainstitute.org/yoganew/ganesh-chaturthi-and-sattvic-diet",
  "https://theyogainstitute.org/what-is-sattvic-diet/eight",
  "https://theyogainstitute.org/3-months-advanced-teacher-training-courseRegister",
  "https://theyogainstitute.org/product-tag/pranayama",
  "https://theyogainstitute.org/blog/patanjali-yoga-sutra-ch1-sutra-19-parisamvad",
  "https://theyogainstitute.org/yoga-sutra-certificate-course",
  "https://theyogainstitute.org/blog/smt-hansaji-on-misconceptions-about-yoga-at-the-satsang-27th-jan-2013",
  "https://theyogainstitute.org/How",
  "https://theyogainstitute.org/celebrating-4th-idy-with-bmc-officials-educators",
  "https://theyogainstitute.org/decoration-at-the-function",
  "https://theyogainstitute.org/purchase-history",
  "https://theyogainstitute.org/couples-classes-registration-form",
  "https://theyogainstitute.org/on-campus-courses",
  "https://theyogainstitute.org/professional-education/training-certification/improving-asthma-for-all",
  "https://theyogainstitute.org/wp-content/uploads/2018/04/3mttc-syllabus.pdf",
  "https://theyogainstitute.org/gaur-gopal-das-at-harmony-fest",
  "https://theyogainstitute.org/juhu-vile-parle",
  "https://theyogainstitute.org/product/online-yoga-classes-for-kids",
  "https://theyogainstitute.org/product/online-regular-guided-meditation-classes",
  "https://theyogainstitute.org/tag/letting-go",
  "https://theyogainstitute.org/camp-form-on-campus-residential",
  "https://theyogainstitute.org/yoganew/digital-media",
  "https://theyogainstitute.org/free-ebooks",
  "https://theyogainstitute.org/product/online-cardiac-and-hypertension-health-workshop",
  "https://theyogainstitute.org/can-i-teach-yoga-online",
  "https://theyogainstitute.org/yoganew/the-price-for-honesty",
  "https://theyogainstitute.org/celebrating-4th-international-day-of-yoga-at-mantralaya",
  "https://theyogainstitute.org/Yo",
  "https://theyogainstitute.org/code-of-conduct-3-months-teachers-training-course",
  "https://theyogainstitute.org/quotes/happiness-3",
  "https://theyogainstitute.org/cart",
  "https://theyogainstitute.org/yoganew/q-a-at-the-satsang-harmony-in-marriage",
  "https://theyogainstitute.org/theyogainstitute.org/patanjali-yoga-sutra-2-11-parisamvad",
  "https://theyogainstitute.org/tag/62d65efc1c38b19586c5b524",
  "https://theyogainstitute.org/yoganew/germans-are-here-15th-may-2016",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-2nd-6th-june-2014",
  "https://theyogainstitute.org/tag/yoga-teacher",
  "https://theyogainstitute.org/product/online-pregnancy-camp",
  "https://theyogainstitute.org/tag/674450ba8643300bf72f7247",
  "https://theyogainstitute.org/swadhaya-802x1024",
  "https://theyogainstitute.org/yoganew/carrot-and-raisin-tartlets",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-21st-september-27th-september",
  "https://theyogainstitute.org/part-time-ttc-200-hrs-online-english-lp",
  "https://theyogainstitute.org/yoganew/restorative-winter-yoga-to-fight-depression",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-online-camp-form",
  "https://theyogainstitute.org/5-kleshas-root-causes-ofsuffering-in-life",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-yoga-for-the-golden-years-at-the-santsang-17th-feb-2013",
  "https://theyogainstitute.org/celebrating-4th-international-day-of-yoga-at-cipla",
  "https://theyogainstitute.org/yoganew/qa-pratyahara",
  "https://theyogainstitute.org/product-tag/nutrition-workshop",
  "https://theyogainstitute.org/tag/reduce-injury",
  "https://theyogainstitute.org/yoganew/summer-yoga-camps-for-kids",
  "https://theyogainstitute.org/ayurveda-workshop-registration-form",
  "https://theyogainstitute.org/weekend-teacher-training-course-july-sept-lp",
  "https://theyogainstitute.org/blog/participation-in-citizens-movement-for-equal-streets-mumbai-week-2",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-29th-june-5th-july",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-hindi-online-lp",


  "https://theyogainstitute.org/yoganew/quality-council-of-india-qci",
  "https://theyogainstitute.org/yoganew/trataka-yogic-eye-care",
  "https://theyogainstitute.org/tag/ashtanga-yoga",
  "https://theyogainstitute.org/hong-kong",
  "https://theyogainstitute.org/thank-you-ttc-registration",
  "https://theyogainstitute.org/yoganew/paramhamsa-madhavadasji",
  "https://theyogainstitute.org/blog/hansaji-talking-on-pratyahara",
  "https://theyogainstitute.org/product-tag/december",
  "https://theyogainstitute.org/yoganew/six-simple-ways-to-clear-negativity",
  "https://theyogainstitute.org/yoganew/little-drops-of-water",
  "https://theyogainstitute.org/uruguay",
  "https://theyogainstitute.org/product-category/camps/wellness-camps/bhavas-workshop",
  "https://theyogainstitute.org/yoganew/launch-of-yogasattva-monthly-e-newsletter-of-the-yoga-institute-tyi-india",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-31st-aug-3rd-sept-2013",
  "https://theyogainstitute.org/yoganew/replace-your-cup-of-regular-tea-with-healthy-herbal-tea",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-14th-september-19th-september",
  "https://theyogainstitute.org/yoganew/how-to-control-anger-by-practising-saucha",
  "https://theyogainstitute.org/yogis-panel-at-harmony-fest",
  "https://theyogainstitute.org/yoganew/care-of-the-eyes-through-yoga-kriya-trataka",
  "https://theyogainstitute.org/celebrating-international-day-of-yoga-at-podar-school",
  "https://theyogainstitute.org/yoganew/parenting-positively-7-handy-tips",
  "https://theyogainstitute.org/celebrating-international-day-of-yoga-at-axis-securities-2017",
  "https://theyogainstitute.org/childrens-regular-classes-on-campus",
  "https://theyogainstitute.org/quotes/attachment/22",
  "https://theyogainstitute.org/blog/dr-jayadeva-on-satya-at-the-satsang-12th-may-2013?replytocom=386",
  "https://theyogainstitute.org/blog/pratipaksha-bhavana-nispandabhava-anitya-bhavana-satsang",
  "https://theyogainstitute.org/yoganew/yogapsychology",
  "https://theyogainstitute.org/yoganew/yoga-glowing-skin",
  "https://theyogainstitute.org/yoganew/qa-pratyahara",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-49-parisamvad",
  "https://theyogainstitute.org/yoganew/can-yoga-cure-hypothyroidism",
  "https://theyogainstitute.org/specific-health-camps",
  "https://theyogainstitute.org/yoganew/top-10-tips-to-reduce-weight",
  "https://theyogainstitute.org/yoganew/summer-yoga-camps-for-kids",
  "https://theyogainstitute.org/what-is-sattvic-diet/prize",
  "https://theyogainstitute.org/thank-you-900-hours-ttc-on-campus-lp",
  "https://theyogainstitute.org/yoganew/qa-on-asteya-at-the-satsang-19th-may-2013",
  "https://theyogainstitute.org/yoganew/5-things-to-quit-right-away",
  "https://theyogainstitute.org/yoganew/goal-in-life-satsang",
  "https://theyogainstitute.org/yoganew/care-of-the-nose",
  "https://theyogainstitute.org/home-tuitions/hometuition@theyogainstitute.in",
  "https://theyogainstitute.org/what-is-sattvic-diet/kapalbhati",
  "https://theyogainstitute.org/meditation-workshop/Subscribe",
  "https://theyogainstitute.org/21days",
  "https://theyogainstitute.org/yoganew/rediscovering-myself-through-yoga",
  "https://theyogainstitute.org/what-is-sattvic-diet/subhankar",
  "https://theyogainstitute.org/what-is-sattvic-diet/basic",
  "https://theyogainstitute.org/mit-world-peace-university-pune",
  "https://theyogainstitute.org/blog/hansaji-talking-guru-shishya-guru-purnima-day",
  "https://theyogainstitute.org/yoganew/hansaji-on-asteya-at-the-satsang-19th-may-2013",
  "https://theyogainstitute.org/yoganew/hansaji-talking-on-change-yourself",
  "https://theyogainstitute.org/what-is-sattvic-diet/coldplay",
  "https://theyogainstitute.org/guide-to-yoga-meditation-front-cover-150x150",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-on-campus-englishWatch",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-10th-august-16th-august",
  "https://theyogainstitute.org/yoganew/how-to-control-our-mind-and-stop-mental-chatter",
  "https://theyogainstitute.org/yoganew/unexpected-benefits-of-yoga-for-athletes",
  "https://theyogainstitute.org/yoganew/hansaji-on-positive-thinking-at-the-satsang",
  "https://theyogainstitute.org/yoganew/weekly-update-dr-jayadeva-talking-on-yoga-2-8-march-2013",
  "https://theyogainstitute.org/first-qci-certified-yoga-teacher-training-school-the-yoga-institute-mumbai/2-the-yoga-institute-book-store",
  "https://theyogainstitute.org/camps_and_workshops.htm",
  "https://theyogainstitute.org/yoganew/the-yoga-institute-tyi-yoga-teacher-training-course-level-1",
  "https://theyogainstitute.org/yoganew/a-special-camp-at-the-yoga-institute-the-reach-out-camp",
  "https://theyogainstitute.org/yoganew/diwali-special-dates-pistachios-delights",
  "https://theyogainstitute.org/yoganew/bhagwad-gita-sloka-2-58-parisamvad",
  "https://theyogainstitute.org/yoganew/you-are-what-you-eat",
  "https://theyogainstitute.org/what-is-sattvic-diet/anu",
  "https://theyogainstitute.org/what-is-sattvic-diet/english",
  "https://theyogainstitute.org/author/prasenjt",
  "https://theyogainstitute.org/yoganew/simple-act-of-correct-breathing-things-you-should-know",
  "https://theyogainstitute.org/product-category/camps/health-camps/orthopaedic-camp",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-yogendra-6-12-april-2013",
  "https://theyogainstitute.org/blog/parikarmas-embellishments",
  "https://theyogainstitute.org/celebrating-4th-international-day-of-yoga-at-rotary",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-talking-purusha-prakruti",
  "https://theyogainstitute.org/yoganew/anitya-bhavana-reflection-technique",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-2-9-parisamvad",
  "https://theyogainstitute.org/yoganew/4-ways-yoga-can-help-heal-addiciton",
  "https://theyogainstitute.org/yoganew/bhagavad-gita-chapter-10-shloka-31",
  "https://theyogainstitute.org/yoganew/dealing-with-an-unfair-boss",
  "https://theyogainstitute.org/yoganew/santosh-contentment",
  "https://theyogainstitute.org/500-hrs-yoga-ttc-intermediate-level-online-camp-form-english",
  "https://theyogainstitute.org/21-days-far",
  "https://theyogainstitute.org/yoganew/yoga-for-eyes",
  "https://theyogainstitute.org/10-life-lessons",
  "https://theyogainstitute.org/200-hrs-..",
  "https://theyogainstitute.org/yoganew/weekly-update-dr-jayadeva-talking-on-yoga-19th-25th-jan-2013",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-yoga-dr-jayadeva-25th-30th-may",
  "https://theyogainstitute.org/yoganew/importance-of-thought-process-vichara",
  "https://theyogainstitute.org/yoganew/10-yogic-ideas-to-celebrate-earth-day",
  "https://theyogainstitute.org/yoganew/ardhamatsyendrasana-the-spinal-half-twist-posture",
  "https://theyogainstitute.org/yoganew/restorative-winter-yoga-to-fight-depression",
  "https://theyogainstitute.org/yoganew/pranayama-puraka-prolonged-inhalation",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-40-parisamvad",
  "https://theyogainstitute.org/what-is-sattvic-diet/Adama",
  "https://theyogainstitute.org/yoganew/reduce-neck-fat-recommended-yoga-asanas-effective-yogic-tips",
  "https://theyogainstitute.org/product-category/camps/online-camps",
  "https://theyogainstitute.org/21-times-improved-living-course-online",
  "https://theyogainstitute.org/one-month-ttc/Download",
  "https://theyogainstitute.org/5-powe",
  "https://theyogainstitute.org/yoganew/smt-hansaji-yogendra-on-purushartha-motivations-at-the-satsang",
  "https://theyogainstitute.org/yoganew/curtain-raiser-to-international-yoga-day-icai-mega-event",
  "https://theyogainstitute.org/tag/artha",
  "https://theyogainstitute.org/yoganew/difference-between-yoga-and-meditation",
  "https://theyogainstitute.org/yoganew/few-yoga-handy-tips-for-flight-seats",
  "https://theyogainstitute.org/mobile/patanjali-yoga-sutra-1-51-parisamvad",
  "https://theyogainstitute.org/yoganew/teacher-training-courses",
  "https://theyogainstitute.org/product-category/regular-classes",
  "https://theyogainstitute.org/yoganew/what-is-true-meditation",
  "https://theyogainstitute.org/yoganew/maitri-bhava-and-yoga",
  "https://theyogainstitute.org/yoganew/ayurveda-course",
  "https://theyogainstitute.org/harmonyfest/food-stalls",
  "https://theyogainstitute.org/yoganew/egyptian-yoga",
  "https://theyogainstitute.org/yoganew/two-year-ttc",
  "https://theyogainstitute.org/yoganew/yogamudra",
  "https://theyogainstitute.org/yoganew/france",
  "https://theyogainstitute.org/wiki/Adapted_physical_education",
  "https://theyogainstitute.org/what-is-sattvic-diet/refer",
  "https://theyogainstitute.org/seven-month-ttc-lp",
  "https://theyogainstitute.org/7-days-camp/Watch",
  "https://theyogainstitute.org/21-days-better-living-course-batch-4Register",
  "https://theyogainstitute.org/ujjayi",
  "https://theyogainstitute.org/part-time-ttc-200-hrs-online-english-lp",
  "https://theyogainstitute.org/what-is-sattvic-diet/mother",
  "https://theyogainstitute.org/yoganew/bhagwad-gita-slokas-2-64-2-65-parisamvad",
  "https://theyogainstitute.org/yoganew/yogic-principles-reduces-divorce-rates",
  "https://theyogainstitute.org/patanjali-yoga-sutra-1-39",
  "https://theyogainstitute.org/yoganew/childrens-camp-from-april-to-june-2011",
  "https://theyogainstitute.org/celebrating-4th-international-day-of-yoga-at-cipla",
  "https://theyogainstitute.org/counselling-services",
  "https://theyogainstitute.org/smt-hansaji-yogendras-72nd-birthday-celebrations-2019",
  "https://theyogainstitute.org/what-is-sattvic-diet/mdickie",
  "https://theyogainstitute.org/21-days-better-living-courseWatch",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-ahar-vihar-achar-vichar",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-2-26-parisamvad",
  "https://theyogainstitute.org/yoganew/yoga-healing-menopause-management",
  "https://theyogainstitute.org/yoganew/aparigraha",
  "https://theyogainstitute.org/virtual-tour-centennial-chronicles",

   "https://theyogainstitute.org/what-is-sattvic-diet/prashi",
  "https://theyogainstitute.org/789579/kids-yoga-exercises",
  "https://theyogainstitute.org/what-is-sattvic-diet/meld",
  "https://theyogainstitute.org/product-tag/7-days-camp",
  "https://theyogainstitute.org/what-is-sattvic-diet/f1-11Brahmi",
  "https://theyogainstitute.org/form-sample",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-29-parisamvad",
  "https://theyogainstitute.org/yoganew/yoga-sutra-ch-1-sutra-9-parisamvad",
  "https://theyogainstitute.org/yoganew/bhagvad-gita-3-9-in-daily-life",
  "https://theyogainstitute.org/yoganew/trataka-yogic-eye-care",
  "https://theyogainstitute.org/free-yoga-online-workshops",
  "https://theyogainstitute.org/yoga-asana",
  "https://theyogainstitute.org/what-is-sattvic-diet/viparita",
  "https://theyogainstitute.org/yoganew/yoga-therapeutics-to-cure-migraines-headaches",
  "https://theyogainstitute.org/yoganew/what-is-bhastrika-pranayama-and-its-benefits",
  "https://theyogainstitute.org/yoganew/tranquil-state-of-mind-dr-jayadeva-yogendra",
  "https://theyogainstitute.org/yoganew/qa-on-santosh-contentment-at-the-satsang",
  "https://theyogainstitute.org/yoganew/holiday-yoga-camp-at-wadia-vachha-school",
  "https://theyogainstitute.org/yoganew/a-true-story-of-by-passing-the-by-pass",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-talking-on-brahmacharya",
  "https://theyogainstitute.org/yoganew/yashtikasana-the-stick-posture",
  "https://theyogainstitute.org/yoganew/caught-up-with-wrong-routines",
  "https://theyogainstitute.org/yoganew/5th-international-day-of-yoga",
  "https://theyogainstitute.org/yoganew/hansaji-on-are-we-spiritual",
  "https://theyogainstitute.org/yoganew/matsyasana-the-fish-pose",
  "https://theyogainstitute.org/m/importance-of-the-spine-in-yoga",
  "https://theyogainstitute.org/product-tag/life-management-camp",
  "https://theyogainstitute.org/product-tag/online-level-2",
  "https://theyogainstitute.org/yoganew/beauty-the-natural-way",
  "https://theyogainstitute.org/yoganew/lions-club-womens-camp",
  "https://theyogainstitute.org/yoganew/happy-mothers-day-tyi",
  "https://theyogainstitute.org/product-tag/january",
  "https://theyogainstitute.org/what-is-sattvic-diet/star",
  "https://theyogainstitute.org/wa/tyi-support",
  "https://theyogainstitute.org/what-is-sattvic-diet/two",
  "https://theyogainstitute.org/yoganew/yoga-kumbha-at-ujjain",
  "https://theyogainstitute.org/500-hrs-online-yoga-teacher-training-course-intermediate-level/Watch",
  "https://theyogainstitute.org/what-is-sattvic-diet/Recent",
  "https://theyogainstitute.org/what-is-sattvic-diet/indian",
  "https://theyogainstitute.org/what-is-sattvic-diet/12",
  "https://theyogainstitute.org/product-category/swadhyaya",
  "https://theyogainstitute.org/certificate-program-on-yoga-for-cancer-registration-form",
  "https://theyogainstitute.org/thank-you-one-month-ttc-200-hours-registration-sp",
  "https://theyogainstitute.org/yoganew/weekly-update-dr-jayadeva-talking-on-yoga-2nd-8th-feb-2013",
  "https://theyogainstitute.org/weekend-teacher-training-course-july-sept-lp",
  "https://theyogainstitute.org/yoga-therapy-course/Register",
  "https://theyogainstitute.org/what-is-sattvic-diet/ind",
  "https://theyogainstitute.org/yogatherapycourse",
  "https://theyogainstitute.org/yoganew/hansaji-on-sanskaras-values-at-the-satsang-13th-jan-2013",
  "https://theyogainstitute.org/yoganew/yoga-tips-for-nursing-moms",
  "https://theyogainstitute.org/suryasana2020",
  "https://theyogainstitute.org/yoganew/yoga-for-people-with-special-needs",
  "https://theyogainstitute.org/yoganew/hansaji-on-balanced-state-of-mind-at-the-satsang",
  "https://theyogainstitute.org/yoganew/chakrasana-the-wheel-pose",
  "https://theyogainstitute.org/product-tag/july-21-days-better-living-course",
  "https://theyogainstitute.org/yoganew/six-simple-ways-to-clear-negativity",
  "https://theyogainstitute.org/yoganew/yoga-balancing-home-profession",
  "https://theyogainstitute.org/yoganew/mysticism-is-mysterious-2",
  "https://theyogainstitute.org/celebrating-3rd-international-day-of-yoga-at-air-cargo/#!",
  "https://theyogainstitute.org/sukhwinder-singh-addressing-the-sudience",
  "https://theyogainstitute.org/certificate-yoga-therapy-course-onlineWatch",
  "https://theyogainstitute.org/200-hrs-parttime-ttc-online-english/Register",
  "https://theyogainstitute.org/yoganew/yogic-diet-ahara-recipe-for-herbal-tea",
  "https://theyogainstitute.org/yoganew/100-300-hour-yoga-teacher-training",
  "https://theyogainstitute.org/yoganew/top-5-yoga-poses-for-women-empowerment",
  "https://theyogainstitute.org/yoganew/prevention-of-disease",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-balanced-state-of-mind-at-the-satsang-30th-dec-2012",
  "https://theyogainstitute.org/what-is-sattvic-diet/free",
  "https://theyogainstitute.org/7-effective-yoga-poses-for-hiatal-hernia",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english/1mttc@theyogainstitute.org",
  "https://theyogainstitute.org/yoganew/home-tuitions",
  "https://theyogainstitute.org/thank-you-one-month-ttc-registration",
  "https://theyogainstitute.org/newsletter/yogasattav-feb-theyogainstitute",
  "https://theyogainstitute.org/marriage-relations-life-lessons/sutra-1-33",
  "https://theyogainstitute.org/verify_trustscam_com_2ed9697f1b76193889d53dd43f4f5b45.html",
  "https://theyogainstitute.org/faqs",
  "https://theyogainstitute.org/celebrating-4th-international-day-of-yoga-at-powai",
  "https://theyogainstitute.org/yoganew/seven-month-ttc",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-talking-pratyahara",
  "https://theyogainstitute.org/200-hrs-component-time-ttc-on-campus-english",
  "https://theyogainstitute.org/blog/weekly-update-talks-yoga-dr-jayadeva-18th-may-23rd-may",
  "https://theyogainstitute.org/product-tag/march",
  "https://theyogainstitute.org/21-days-better",
  "https://theyogainstitute.org/yoganew/coronary-heart-disease",
  "https://theyogainstitute.org/yoganew/viparitkarni-the-inverted-posture",
  "https://theyogainstitute.org/celebrating-3rd-international-day-of-yoga-andheri-centre",
  "https://theyogainstitute.org/yoganew/understanding-ashtanga-yoga",
  "https://theyogainstitute.org/yoganew/hansaji-on-santosh-contentment-at-the-satsang-16th-june-2013",
  "https://theyogainstitute.org/yoganew/carrot-and-raisin-tartlets",
  "https://theyogainstitute.org/what-is-sattvic-diet/special",
  "https://theyogainstitute.org/what-is-sattvic-diet/couples",
  "https://theyogainstitute.org/10 Fitness Goals and Weight loss Management",
  "https://theyogainstitute.org/agent/tyi-support",
  "https://theyogainstitute.org/kalyan",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-hindi-online-lp",
  "https://theyogainstitute.org/excellence-award-from-rotary-international",
  "https://theyogainstitute.org/kandivali",
  "https://theyogainstitute.org/Register",
  "https://theyogainstitute.org/what-is-sattvic-diet/Summer",
  "https://theyogainstitute.org/what-is-sattvic-diet/01",
  "https://theyogainstitute.org/900-hours-advanced-teacher-training-course/Register",
  "https://theyogainstitute.org/yoganew/yogendra-paschimottanasana",
  "https://theyogainstitute.org/yoganew/real-yoga",
  "https://theyogainstitute.org/yoganew/justice-dharmadhikari-on-truth-and-yoga",
  "https://theyogainstitute.org/yoganew/get-rid-of-stubborn-belly-fat",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-talking-overcoming-ego",
  "https://theyogainstitute.org/thank-you-one-month-ttc-200-hours-lp",
  "https://theyogainstitute.org/what-is-bhastrika-pranayama",
  "https://theyogainstitute.org/level-3-diploma-program-in-yoga-counselling",
  "https://theyogainstitute.org/newsletter/yogasattva-june2018",
  "https://theyogainstitute.org/blog/implicit-obedience-to-the-guru",
  "https://theyogainstitute.org/product-category/month/june",
  "https://theyogainstitute.org/celebrating-4th-idy-at-swami-vivekanand-school",
  "https://theyogainstitute.org/yoganew/how-to-do-halasana-easily",
  "https://theyogainstitute.org/yoganew/tyi-international-day-of-yoga-2018-mega-event-at-bhopal",
  "https://theyogainstitute.org/yoganew/yoga-sutra-isvara-pranidhanat-va-1-23",
  "https://theyogainstitute.org/yoganew/yoga-for-glowing-face",
  "https://theyogainstitute.org/yoganew/nature-trail",
  "https://theyogainstitute.org/smt-hansaji-j-yogendra-conferred-upon-doctor-of-philosophy-phd",
  "https://theyogainstitute.org/blog/patanjali-yoga-sutra-2-18-parisamvad",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-4th-10th-may-2013",
  "https://theyogainstitute.org/yoganew/yoga-for-beginners-by-dr-jayadeva-yogendra",
  "https://theyogainstitute.org/yoganew/reduce-arm-fat-yogic-tips",
  "https://theyogainstitute.org/yoganew/ganesh-chaturthi-and-sattvic-diet",
  "https://theyogainstitute.org/yoganew/the-yoga-institute-conducted-camp-for-mithibai-college-b-a-philiosophy-students",
  "https://theyogainstitute.org/happy-teachers-day-2017/smt-hansaji-jayadeva-yogendra-director-of-the-yoga-institute",
  "https://theyogainstitute.org/yoganew/dr-jayadeva-on-yoga-for-the-golden-years-at-the-santsang-17th-feb-2013",
  "https://theyogainstitute.org/yoganew/shri-yogendraji-founder-of-the-yoga-institute-santacruz-mumbai-india",
  "https://theyogainstitute.org/yoganew/can-yoga-treat-severe-addictions-like-alcoholism-or-drug-abuse",
  "https://theyogainstitute.org/5th-qci-steering-committee-meeting/5th-qci-steering-committee-meeting",
  "https://theyogainstitute.org/yoganew/octogenarian-teacher-with-teenage-sparkle",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-2-11-parisamvad",
  "https://theyogainstitute.org/yoganew/householder-yoga-why-convention-2012",
  "https://theyogainstitute.org/yoganew/resolve-work-conflict-the-yogic-way",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-2-1-parisamvad",
  "https://theyogainstitute.org/yoganew/international-yoga-day-2015",
  "https://theyogainstitute.org/yoganew/yoga-sutra-1-03-parisamvad",
  "https://theyogainstitute.org/yoganew/secret-to-happy-marriage",
  "https://theyogainstitute.org/product-tag/nutrition-workshop",
  "https://theyogainstitute.org/yoganew/qa-yoga-golden-years",

  "https://theyogainstitute.org/yoganew/can-we-be-contented",
  "https://theyogainstitute.org/thank-you-weekend-ttc-registration-sp",
  "https://theyogainstitute.org/lower-back-pain-and-yoga/Accessed",
  "https://theyogainstitute.org/hansaji-birthday-celebration",
  "https://theyogainstitute.org/bhujangasana-the",
  "https://theyogainstitute.org/the-household-yogi-712x1024",
  "https://theyogainstitute.org/one-month-ttcRegister",
  "https://theyogainstitute.org/what-is-sattvic-diet/grand",
  "https://theyogainstitute.org/what-is-sattvic-diet/javelin",
  "https://theyogainstitute.org/lifetime-achievement-award",
  "https://theyogainstitute.org/200-hours-1-month-ttc-sp/1mttc@theyogainstitute.org",
  "https://theyogainstitute.org/what-is-sattvic-diet/desi",
  "https://theyogainstitute.org/yoganew/sample-4",
  "https://theyogainstitute.org/yoganew/headache",
  "https://theyogainstitute.org/yoga-total-health",
  "https://theyogainstitute.org/thank-you-7-months-ttc-registration",
  "https://theyogainstitute.org/yoganew/weekly-update-talks-on-yoga-by-dr-jayadeva-29th-june-5th-july",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-on-campus-english-march",
  "https://theyogainstitute.org/ayurveda-workshop-registration-form",
  "https://theyogainstitute.org/2016/11",
  "https://theyogainstitute.org/what-is-sattvic-diet/round",
  "https://theyogainstitute.org/what-is-sattvic-diet/let",
  "https://theyogainstitute.org/product-category/ttc",
  "https://theyogainstitute.org/thank-you-ttc-registration",
  "https://theyogainstitute.org/qwerty",
  "https://theyogainstitute.org/yoganew/international-womens-day",
  "https://theyogainstitute.org/yoganew/bhagwad-gita-2-51-2-52",
  "https://theyogainstitute.org/celebrating-4th-international-day-of-yoga-at-podar-school",
  "https://theyogainstitute.org/yoganew/sharing-an-experience",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-38-parisamvad",
  "https://theyogainstitute.org/blog/simple-words",
  "https://theyogainstitute.org/japanese-group/an-auspicious-japanese-ceremony-conducted-at-the-yoga-institute-in-presence-of-yoga-guru-smt-hansaji-by-their-guru-1",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-2-22-parisamvad",
  "https://theyogainstitute.org/yoganew/true-story-of-a-miracle-yogi",
  "https://theyogainstitute.org/yoganew/qa-on-yoga-a-medical-therapy",
  "https://theyogainstitute.org/yoganew/tantra-and-yoga",
  "https://theyogainstitute.org/one-month-ttc/Watch",
  "https://theyogainstitute.org/6-yoga",
  "https://theyogainstitute.org/Yoga",
  "https://theyogainstitute.org/participation-in-citizens-movement-for-equal-streets-mumbai-week-2/relaxation-session-practicing-makarasana",
  "https://theyogainstitute.org/yoganew/integral-chakra-psychology",
  "https://theyogainstitute.org/yoganew/fitness-and-yoga-holistic-approach",
  "https://theyogainstitute.org/yoganew/yoga-for-students-tips-to-improve-concentration-memory-during-exams",
  "https://theyogainstitute.org/yoganew/1-month-yoga-routine-for-getting-into-shape-for-ganesh-chaturthi",
  "https://theyogainstitute.org/yoganew/smt-hansaji-on-harmony-in-marriage-at-the-satsang-16th-dec-2012",
  "https://theyogainstitute.org/yoganew/paramhamsa-madhavadasji",
  "https://theyogainstitute.org/what-is-sattvic-diet/J",
  "https://theyogainstitute.org/weekend_class.htm",
  "https://theyogainstitute.org/product-category/month/march",
  "https://theyogainstitute.org/product-category/books",
  "https://theyogainstitute.org/blog/dr-jayadeva-on-niyama-at-the-satsang-10th-march-2013-2",
  "https://theyogainstitute.org/yoga-guru-smt-hansaji-and-international-yoga-fest/sutra-2",
  "https://theyogainstitute.org/yoganew/yoga-for-beginners-top-3-tips-on-how-to-do-yoga",
  "https://theyogainstitute.org/yoganew/why-should-anyone-join-yoga-teachers-training",
  "https://theyogainstitute.org/yoganew/hansaji-on-satya-at-the-satsang-12th-may-2013",
  "https://theyogainstitute.org/product-tag/enhance-immunity-with-ayurveda-workshop",
  "https://theyogainstitute.org/international-yoga-day-2016",
  "https://theyogainstitute.org/yoganew/inauguration-organic-waste-converter-report",
  "https://theyogainstitute.org/what-is-sattvic-diet/8",
  "https://theyogainstitute.org/what-is-sattvic-diet/DIY",
  "https://theyogainstitute.org/yoganew/impressions-of-the-7-days-residential-camp",
  "https://theyogainstitute.org/yoganew/how-to-manage-weight-and-stress-with-yoga",
  "https://theyogainstitute.org/yoganew/summer_yoga_camps_for_children_april2014",
  "https://theyogainstitute.org/yoganew/vairagaya-bhava-objectivity-yogamudra",
  "https://theyogainstitute.org/yoganew/patanjali-yoga-sutra-1-42-parisamvad",
  "https://theyogainstitute.org/yoganew/awareness-is-the-key-2",
  "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english/Watch",
  "https://theyogainstitute.org/yoganew/mahavir-jayanti-wishes-to-everyone",
  "https://theyogainstitute.org/yoganew/using-yoga-to-enhance-flexibility",
  "https://theyogainstitute.org/blog/hansaji-talking-on-pratyahara",
  "https://theyogainstitute.org/blog/patanjali-yoga-sutra-1-30-parisamvad",
  "https://theyogainstitute.org/blog/why-difficult-asanas",
  "https://theyogainstitute.org/yoganew/top-5-benefits-of-meditation",
  "https://theyogainstitute.org/yoganew/yoga-chow-chow-of-modern-day"


   ]

  let links301 = [
    "https://theyogainstitute.org/patanjali-yoga-sutra-ch-1-sutra-10-parisamvad",
    "https://theyogainstitute.org/dr-jayadeva-talking-saucha-purity",
    "https://theyogainstitute.org/how-can-yoga-help-students-alleviate-examination-stress-and-make-them-perform-better",
    "https://theyogainstitute.org/patanjali-yoga-sutra-2-5-parisamvad",
    "https://theyogainstitute.org/patanjali-yoga-sutra-1-51-parisamvad",
    "https://theyogainstitute.org/can-yoga-help-in-psychosomatic-disease",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/the-yoga-institute-conducted-yoga-sessions-for-sadhu-vaswani-mission",
    "https://theyogainstitute.org/diy-quick-top-5-yoga-tips-to-keep-the-exam-stress-at-bay",
    "https://theyogainstitute.org/weekly-update-talks-yoga-dr-jayadeva-14th-april-17th-april",
    "https://theyogainstitute.org/conditioning-yoga",
    "https://theyogainstitute.org/yoga-tips-reduce-side-fat",
    "https://theyogainstitute.org/dishonesty-is-not-the-best-policy-dr-jayadeva-yogendra",
    "https://theyogainstitute.org/patanjali-yoga-sutra-1-30-parisamvad",
    "https://theyogainstitute.org/corporate-workshops",
    "https://theyogainstitute.org/importance-of-sleep-in-our-daily-life",
    "https://theyogainstitute.org/drawing-a-line",
    "https://theyogainstitute.org/qa-on-change-yourself",
    "https://theyogainstitute.org/dr-jayadeva-on-paramhamsa-madhavadasji-overcoming-bad-habits-at-the-satsang-3rd-jan-2013",
    "https://theyogainstitute.org/weekly-update-talks-on-yoga-by-dr-jayadeva-yogendra-8th-11th-june-2013",
    "https://theyogainstitute.org/weekly-update-talks-yoga-dr-jayadeva-6th-april-10th-april",
    "https://theyogainstitute.org/weekly-update-talks-yoga-dr-jayadeva-30th-march-4th-april",
    "https://theyogainstitute.org/q-a-on-sanskaras-values-at-the-satsang-13th-jan-2013",
    "https://theyogainstitute.org/hansaji-talking-saints-india",
    "https://theyogainstitute.org/june-2011-editorial",
    "https://theyogainstitute.org/weekly-update-talks-on-yoga-by-dr-jayadeva-18-24-may-2013",
    "https://theyogainstitute.org/weekly-update-talks-on-yoga-by-dr-jayadeva-24th-30th-aug-2013",
    "https://theyogainstitute.org/dr-jayadeva-on-positive-thinking-at-the-satsang",
    "https://theyogainstitute.org/sincere-commitment",
    "https://theyogainstitute.org/dr-jayadeva-talking-on-tension-and-relaxation",
    "https://theyogainstitute.org/dr-jayadeva-on-sanskaras-values-at-the-satsang-13th-jan-2013",
    "https://theyogainstitute.org/qa-on-saints-of-india-at-the-satsang-14th-april-2013",
    "https://theyogainstitute.org/every-moment-a-wonder",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/konasana-the-angle-pose-a-guide-to-konasana-benefits-and-techniques",
    "https://theyogainstitute.org/weight-management-workshop",
    "https://theyogainstitute.org/4th-international-day-of-yoga-celebrations-2018",
    "https://theyogainstitute.org/konasana-the-angle-pose-a-guide-to-konasana-benefits-and-techniques",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/21-days-better-living-course-batch-3",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/success-mantra-learn-meditation",
    "https://theyogainstitute.org/practical-yogic-guidelines-to-beat-stress",
    "https://theyogainstitute.org/happy-harmony-fest-and-ringing-in-the-new-year-2019",
    "https://theyogainstitute.org/patanjali-yoga-sutra-1-38-parisamvad",
    "https://theyogainstitute.org/terms-and-conditions",
    "https://theyogainstitute.org/summer-camp-for-kids-5-to-12-years",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/free-yoga-camps-may-june-2015",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/blogs",
    "https://theyogainstitute.org/7-days-camp",
    "https://theyogainstitute.org/weekend-classes",
    "https://theyogainstitute.org/7-days-camp-english",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/5-powerful-ways-to-hit-the-pause-button",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/7-days-camp",
    "https://theyogainstitute.org/print-media",
    "https://theyogainstitute.org/yoga-sutra-isvara-pranidhanat-va-1-23",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/yoga-and-total-health",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/what-is-sattvic-diet",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english",
    "https://theyogainstitute.org/importance-of-the-spine-in-yoga",
    "https://theyogainstitute.org/the-subconscious-mind",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/what-is-sattvic-diet",
    "https://theyogainstitute.org/900-hours-advanced-teacher-training-course",
    "https://theyogainstitute.org/what-is-sattvic-diet",
    "https://theyogainstitute.org/what-is-sattvic-diet",
    "https://theyogainstitute.org/planning-the-perfect-getaway-for-relaxation",
    "https://theyogainstitute.org/library",
    "https://theyogainstitute.org/know-us-better",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/what-is-sattvic-diet",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/how-to-meditate",
    "https://theyogainstitute.org/5-kleshas-root-causes-of-suffering-in-life",
    "https://theyogainstitute.org/yoga-postures-for-shoulder-pain-and-neck-pain",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/easy-ways-to-ease-anxiety",
    "https://theyogainstitute.org/launch-of-yogasattva-monthly-e-newsletter-of-the-yoga-institute-tyi-india",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/what-is-unconditional-love-do-you-have-it",
    "https://theyogainstitute.org/yoga-and-total-health",
    "https://theyogainstitute.org/patanjali-yoga-sutra-1-33-parisamvad",
    "https://theyogainstitute.org/3-months-advanced-teacher-training-course",
    "https://theyogainstitute.org/shop",
    "https://theyogainstitute.org/few-yoga-handy-tips-for-flight-seats",
    "https://theyogainstitute.org/mother-sita-devis-birth-anniversary-celebrations",
    "https://theyogainstitute.org/3-months-advanced-teacher-training-course",
    "https://theyogainstitute.org/yoga-asanas-dos-and-donts-for-beginners",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/yoga-asanas-dos-and-donts-for-beginners",
    "https://theyogainstitute.org/mystic-mantra-chants",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/fullmoon-meditation",
    "https://theyogainstitute.org/drawing-a-line",
    "https://theyogainstitute.org/dr-jayadeva-on-yoga-for-the-golden-years-at-the-santsang-17th-feb-2013",
    "https://theyogainstitute.org/dr-jayadeva-on-paramhamsa-madhavadasji-overcoming-bad-habits-at-the-satsang-3rd-jan-2013",
    "https://theyogainstitute.org/hansaji-talking-on-asteya-non-stealing",
    "https://theyogainstitute.org/blogs",
    "https://theyogainstitute.org/certificate-yoga-therapy-course-online",
    "https://theyogainstitute.org/weekend-classes",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/guided-meditation",
    "https://theyogainstitute.org/yoga-camps-for-kids",
    "https://theyogainstitute.org/swadhyaya",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/happy-teachers-day-2024",
    "https://theyogainstitute.org/image-gallery",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/empowering-teenage-girls-through-yoga",
    "https://theyogainstitute.org/the-perfect-yoga-poses-to-power-up-your-mornings",
    "https://theyogainstitute.org/sukhwinder-singh-performs-at-the-yoga-institute-santacruz-on-janmashtmi-2016",
    "https://theyogainstitute.org/yoga-therapeutic-for-diabetes",
    "https://theyogainstitute.org/rejuvenating-your-mind-with-meditation",
    "https://theyogainstitute.org/satsang",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english",
    "https://theyogainstitute.org/high-vibration-people-definition-signs-and-how-to-become-one",
    "https://theyogainstitute.org/yoga-halls-rooftop-space",
    "https://theyogainstitute.org/yoga-sutra-1-01-parisamvad",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/ganesh-chaturthi-2024",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/book-store",
    "https://theyogainstitute.org/7-days-camp",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/21-days-better-living-course",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/trataka-yogic-eye-care",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english",
    "https://theyogainstitute.org/900-hours-advanced-teacher-training-course",
    "https://theyogainstitute.org/900-hours-advanced-teacher-training-course",
    "https://theyogainstitute.org/yoga-for-immunity",
    "https://theyogainstitute.org/yoga-asanas-dos-and-donts-for-beginners",
    "https://theyogainstitute.org/200-hrs-part-time-ttc-online-english",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/stress-management-camp",
    "https://theyogainstitute.org/7-days-camp",
    "https://theyogainstitute.org/yoga-sutra-1-01-parisamvad",
    "https://theyogainstitute.org/face-yoga-for-beginners",
    "https://theyogainstitute.org/exploring-chakras-and-yoga-practices",
    "https://theyogainstitute.org/reputable-yoga-school-for-yoga-teachers-training",
    "https://theyogainstitute.org/donate",
    "https://theyogainstitute.org/yoga-asanas-for-healthy-mind-and-body",
    "https://theyogainstitute.org/one-month-ttc",
    "https://theyogainstitute.org/7-days-camp-english",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org/one-month-ttc",
    "https://theyogainstitute.org/patanjali-yoga-sutra-2-11-parisamvad",
    "https://theyogainstitute.org/patanjali-yoga-sutra-2-16-parisamvad",
    "https://theyogainstitute.org/wellness",
    "https://theyogainstitute.org/swadhyaya",
    "https://theyogainstitute.org/asana-regular-classes-online",
    "https://theyogainstitute.org",
    "https://theyogainstitute.org"
  ]

  let searchString = `https://theyogainstitute.org${path}`;//in array strings have base URLs so adding here
  let index = links404.indexOf(searchString)
 if (index !== -1) {
    //for navigation no need of base URl, so removing here
    return {
      isNavigate: true,
      path: !links301[index]
        ? '/'
        : links301[index].replace("https://theyogainstitute.org", "") === ""
          ? '/'
          : links301[index].replace("https://theyogainstitute.org", "")
    };
  }
  else {
    return { isNavigate: false }
  }
}

app.use(express.static('build', options))
app.get('*', async (req, res) => {
  const { path: reqPath } = req
  console.log(reqPath);

  const navigationRes = await redirectPage(reqPath);
  if (navigationRes?.isNavigate === true) {
    return res.redirect(301, navigationRes?.path)
  }

  let correctPath = reqPath
  const indexHtmlPath = path.resolve(__dirname, './build/index.html')
  const indexHtml = fs.readFileSync(indexHtmlPath)
  const $ = cheerio.load(indexHtml)
  if (reqPath.endsWith('/') && !(reqPath.length === 1 && reqPath === '/')) correctPath = reqPath.slice(0, -1)
  const metaData = await getMetaData(correctPath)

  // Check if page exists - if metaData is null/undefined, it's a 404
  const is404Page = !metaData || (!metaData.title && !metaData.h1Tag)

  let titleTag = null
  let metaArray = []
  let linkArray = []
  let linkArryBlogs = await getBogLinks()
  let script = ''
  let h1Tag = null
  let h2Tags = []
  let aTags = []
  let courseaTags = []
  let blogATags = []
  let pTag = ''
  let pTagBlog = ''

  if (is404Page) {
    // For 404 pages, inject specific meta tags including noindex
    titleTag = `<title>404 Error - Page Not Found | The Yoga Institute</title>`
    metaArray = [
      `<meta name="robots" content="noindex, nofollow" data-react-helmet="true" />`,
      `<meta name="description" content="The page you are looking for does not exist." data-react-helmet="true" />`,
      `<meta property="og:title" content="404 Error - Page Not Found" data-react-helmet="true" />`,
      `<meta property="og:description" content="The page you are looking for does not exist." data-react-helmet="true" />`,
      `<meta property="og:type" content="website" data-react-helmet="true" />`,
      `<meta name="twitter:card" content="summary" data-react-helmet="true" />`,
      `<meta name="twitter:title" content="404 Error - Page Not Found" data-react-helmet="true" />`,
      `<meta name="twitter:description" content="The page you are looking for does not exist." data-react-helmet="true" />`
    ]
  } else {
    // Normal page meta tags
    if (metaData && metaData.title) titleTag = `<title>${metaData.title}</title>`
    
    // Add canonical link for non-404 pages
    const canonicalUrl = `https://theyogainstitute.org${correctPath}`
    linkArray.push(`<link rel="canonical" href="${canonicalUrl}" data-react-helmet="true" />`)
    
    if (metaData && metaData.links) {
      const existingLinks = metaData.links.map((link) => {
        if (link.rel) return `<link class="meta-heading" rel=${link.rel || ''} href=${RemoveTrailingSlash(link.href) || ''}  />`
      })
      linkArray.push(...existingLinks)
    }
    if (metaData && metaData.metaData) {
      metaArray = metaData.metaData.map((meta) => {
        if (meta.name) return `<meta name="${meta.name || ''}" content="${String(meta.content) || ''}" data-react-helmet="true" />`
        if (meta.property) return `<meta property="${meta.property || ''}" content="${String(meta.content) || ''}" data-react-helmet="true" />`
        return null
      })
    }
    if (metaData && metaData.script) script = metaData.script

    if (metaData && metaData.h1Tag) h1Tag = `<h1 class="meta-heading">${metaData.h1Tag}</h1>`
    if (metaData && metaData.h2Tags) {
      h2Tags = metaData.h2Tags.map((string) => `<h2 class="meta-heading">${string}</h2>`)
    }
    if (metaData && metaData.aTags) {
      aTags = metaData.aTags.map((url) => `<a class="meta-heading" href=${url} >${url}</a>`)
      blogATags = linkArryBlogs.map((url) => `<a class="meta-heading" href=${url} >${url}</a>`)
    }
    if (metaData && metaData.pTag) {
      pTag = `<p class="meta-heading">${metaData.pTag}</p>`
    }
    if (metaData && metaData.pTagBlog) {
      pTagBlog = `<div class="meta-heading">${metaData.pTagBlog}</div>`
    }
    if (metaData && metaData.aTag) {//added to test related courses as anchor tags
      courseaTags = metaData.aTag.map((url) => `<a  class="meta-heading" href=https://theyogainstitute.org/${url} >https://theyogainstitute.org/${url}</a>`)
    }
  }

  let fbMeta = null
  if (reqPath == '/') {
    fbMeta='<meta name="facebook-domain-verification" content="2rnujs1l73gzsee6p372eih8c81lik" />'
  }

  $('head').append([titleTag, script, ...metaArray, ...linkArray, fbMeta])
  $('body').append([h1Tag, ...h2Tags, ...aTags, ...blogATags, pTag, pTagBlog, ...courseaTags])
  
  // Return 301 status for 404 pages as requested
  if (is404Page) {
    res.status(301).send($.html())
  } else {
    res.status(200).send($.html())
  }
})




app.listen(PORT, () => {
  console.log('SERVER Started at port: ' + PORT)
})
