export const authServerClientId = 'prod-tyi-cms'
export const cmsBaseDomain = 'https://cms-prod-be.theyogainstitute.org/v1'
// export const cmsBaseDomain = 'https://39c8-203-132-133-126.ngrok-free.app/v1'
export const authBaseDomain = 'https://www.authserver-prod-be.theyogainstitute.org/v2'
export const ecomBaseDomain = 'https://ecom-prod-be.theyogainstitute.org/v1'
