export const authServerClientId = 'prod-tyi-cms'
export const cmsBaseDomain = 'https://cms-prod-be.theyogainstitute.org/v1'
export const authBaseDomain = 'https://www.authserver-prod-be.theyogainstitute.org/v2'
export const ecomBaseDomain = 'https://ecom-prod-be.theyogainstitute.org/v1'
export const donationBaseDomain = 'https://cms-dev-be.theyogainstituteonline.org/v1'
