const digitalMedia = [
  'https://www.youtube.com/embed/kbZzBee50o4',
  'https://www.youtube.com/embed/0m6yUes-bX8',
  'https://www.youtube.com/embed/Z5y0Fpmi6hI',
  'https://www.youtube.com/embed/RmJbDvHHNW0',
  'https://www.youtube.com/embed/bek2TogdLGo',
  'https://www.youtube.com/embed/XKijiSLP8ro,',
  'https://www.youtube.com/embed/uoKUj8FlLK4,',
  'https://www.youtube.com/embed/_gicmQRJz3g,',
  'https://www.youtube.com/embed/nyuMlb5DI34,',
  'https://www.youtube.com/embed/HamG8QmgXbM,',
  'https://www.youtube.com/embed/LCxTRBY9m8o,',
  'https://www.youtube.com/embed/PhkPCECgFPw,',
  'https://www.youtube.com/embed/sQHWBWQcP2I,',
  'https://www.youtube.com/embed/LCxTRBY9m8o,',
  'https://www.youtube.com/embed/WiG4KB1CzTo,',
  'https://www.youtube.com/embed/GYUyuH9mmJM,',
  'https://www.youtube.com/embed/SXU3J4-j1p0,',
  'https://www.youtube.com/embed/hNzRzNVO6bU,',
  'https://www.youtube.com/embed/4XbsJoRAdiw,',
  'https://www.youtube.com/embed/UtbyHuGE6Kg,',
  'https://www.youtube.com/embed/FrTcJfl6vIE,',
  'https://www.youtube.com/embed/UIdyPj23Ipg,',
  'https://www.youtube.com/embed/mj8YDcJVDdY,',
  'https://www.youtube.com/embed/1bp9t72g1Vc,',
  'https://www.youtube.com/embed/FsX-4xBEPks,',
  'https://www.youtube.com/embed/-FI1ke3GcnA,',
  'https://www.youtube.com/embed/AktMGQPUm_U,',
  'https://www.youtube.com/embed/HVA5QhhZs0E,',
  'https://www.youtube.com/embed/_ub-wl2gGP0,',
  'https://www.youtube.com/embed/GDZFpsUKeXw,',
]

export default digitalMedia