const digitalMedia = [
  {
    video: 'https://www.youtube.com/embed/kbZzBee50o4',
    thumbnail: 'http://img.youtube.com/vi/kbZzBee50o4/hqdefault.jpg',
  },
  { 
    video:'https://www.youtube.com/embed/0m6yUes-bX8',
    thumbnail:'http://img.youtube.com/vi/0m6yUes-bX8/hqdefault.jpg' 
  },
  {
    video:'https://www.youtube.com/embed/Z5y0Fpmi6hI',
    thumbnail:'http://img.youtube.com/vi/Z5y0Fpmi6hI/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/RmJbDvHHNW0',
    thumbnail:'http://img.youtube.com/vi/RmJbDvHHNW0/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/bek2TogdLGo',
    thumbnail:'http://img.youtube.com/vi/bek2TogdLGo/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/XKijiSLP8ro',
    thumbnail:'http://img.youtube.com/vi/XKijiSLP8ro/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/uoKUj8FlLK4',
    thumbnail:'http://img.youtube.com/vi/uoKUj8FlLK4/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/_gicmQRJz3g',
    thumbnail:'http://img.youtube.com/vi/_gicmQRJz3g/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/nyuMlb5DI34',
    thumbnail:'http://img.youtube.com/vi/nyuMlb5DI34/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/HamG8QmgXbM',
    thumbnail:'http://img.youtube.com/vi/HamG8QmgXbM/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/LCxTRBY9m8o',
    thumbnail:'http://img.youtube.com/vi/LCxTRBY9m8o/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/PhkPCECgFPw',
    thumbnail:'http://img.youtube.com/vi/PhkPCECgFPw/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/sQHWBWQcP2I',
    thumbnail:'http://img.youtube.com/vi/sQHWBWQcP2I/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/LCxTRBY9m8o',
    thumbnail:'http://img.youtube.com/vi/LCxTRBY9m8o/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/WiG4KB1CzTo',
    thumbnail:'http://img.youtube.com/vi/WiG4KB1CzTo/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/GYUyuH9mmJM',
    thumbnail:'http://img.youtube.com/vi/GYUyuH9mmJM/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/SXU3J4-j1p0',
    thumbnail:'http://img.youtube.com/vi/SXU3J4-j1p0/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/hNzRzNVO6bU',
    thumbnail:'http://img.youtube.com/vi/hNzRzNVO6bU/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/4XbsJoRAdiw',
    thumbnail:'http://img.youtube.com/vi/4XbsJoRAdiw/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/UtbyHuGE6Kg',
    thumbnail:'http://img.youtube.com/vi/UtbyHuGE6Kg/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/FrTcJfl6vIE',
    thumbnail:'http://img.youtube.com/vi/FrTcJfl6vIE/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/UIdyPj23Ipg',
    thumbnail:'http://img.youtube.com/vi/UIdyPj23Ipg/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/mj8YDcJVDdY',
    thumbnail:'http://img.youtube.com/vi/mj8YDcJVDdY/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/1bp9t72g1Vc',
    thumbnail:'http://img.youtube.com/vi/1bp9t72g1Vc/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/FsX-4xBEPks',
    thumbnail:'http://img.youtube.com/vi/FsX-4xBEPks/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/-FI1ke3GcnA',
    thumbnail:'http://img.youtube.com/vi/-FI1ke3GcnA/hqdefault.jpg'
  }, 
  {
    video:'https://www.youtube.com/embed/AktMGQPUm_U',
    thumbnail:'http://img.youtube.com/vi/AktMGQPUm_U/hqdefault.jpg'
  }, 
  {
    video:'https://www.youtube.com/embed/HVA5QhhZs0E',
    thumbnail:'http://img.youtube.com/vi/HVA5QhhZs0E/hqdefault.jpg'
  }, 
  {
    video:'https://www.youtube.com/embed/_ub-wl2gGP0',
    thumbnail:'http://img.youtube.com/vi/_ub-wl2gGP0/hqdefault.jpg'
  },
  {
    video:'https://www.youtube.com/embed/GDZFpsUKeXw',
    thumbnail:'http://img.youtube.com/vi/GDZFpsUKeXw/hqdefault.jpg'
  },
]

export default digitalMedia
